dist: xenial
services:
  - docker
language: bash
addons:
    apt:
        config:
            retries: true
        update: true
        sources:
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu bionic main universe'
        packages:
            # Install libguestfs-tools to use virt-tar-out command.
            # https://packages.ubuntu.com/bionic/libguestfs-tools
            - libguestfs-tools
env:
    matrix:
        - VERSION=7.2.1511-x86_64
        - VERSION=7.3.1611-x86_64
        - VERSION=7.3.1704-x86_64
        - VERSION=7.6.1901-x86_64

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - ./update.sh "${VERSION}"
